---
# environment can be 'development' or 'production'
# production:
#  - delivers minimized javascript resources
#  - sets JavaScript variable: Lab.config.environment = 'production'
# development:
#  - delivers un-minimized javascript resources
#  - sets JavaScript variable: Lab.config.environment = 'development'
#  - enables rack-livereload
:environment: development
:server:
  development:
    :hostname: localhost:9292
  production:
    :hostname: lab.labframework.org
:jsconfig:
  # This can be set optionally set to true to disable links to DataGames and Java models
  # Can even be done dynamically: LAB_STATIC=true ./script/generate-js-config.rb
  :static: false
  :sharing: true
  :logging: true
  :tracing: false
  :home: http://lab.labframework.org
  # Set :homeForSharing to the host where shared Interactives are found
  # if you don't want to share the ones on the actual server.
  # Example if you host the Interactives on a static S3 site and want the
  # sharing links to point to the same Interactives at http://lab.labframework.org
  :homeForSharing:
  :homeInteractivePath: /interactives.html
  :homeEmbeddablePath: /embeddable.html
  :benchmarkAPIurl: https://script.google.com/macros/s/AKfycbzosXAVPdVRFUrF6FRI42dzQb2IGLnF9GlIbj9gUpeWpXALKgM/exec
  :actualRoot: ""
  :utmCampaign:
  :fontface: Lato
:google_analytics:
  :account_id:
# password and alias for Java siging certificate.
# This self-signed certificate should be replaced with a real certificate
# if the server is delivering signed applets or jars in a production setting.
:java:
  :password: abc123
  :alias: lab-sample-keystore
  :keystore_path: config/lab-sample-keystore.jks
# deploy configuration for working with Amazon Web Services
:deploy:
  :targets:
  - :name: lab
    :url: lab.labframework.org
    :branch: master
    :ec2_flavor: m1.medium
  - :name: lab-dev
    :url: dev.labframework.org
    :branch: master
  :ami: ami-d33163ba
  :ec2_flavor: m1.small
  :group_name: lab
  :zone_domain: labframework.org.
  :zone_records_name: labframework.org
  :pem:
    :name: lab-key
    :path: ~/.ec2

